# Generated by Django 5.0.6 on 2024-06-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contactsubmission_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('frontend', models.CharField(max_length=100)),
                ('backend', models.CharField(max_length=100)),
                ('posted_date', models.DateField()),
                ('posted_by', models.CharField(max_length=100)),
                ('github_link', models.URLField()),
                ('image1', models.ImageField(upload_to='project_images/')),
                ('image2', models.ImageField(upload_to='project_images/')),
                ('image3', models.ImageField(upload_to='project_images/')),
            ],
        ),
    ]
