# Generated by Django 5.0.6 on 2024-06-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('aniket', 'Aniket'), ('kajal', 'Kajal')], max_length=50)),
            ],
        ),
    ]
