# Generated by Django 5.0.6 on 2024-06-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
